#!/bin/bash
#SBATCH --account=bbno-delta-gpu
### GPU options ###
#SBATCH --partition=gpuA100x4      # <- or one of: gpuA100x4 gpuA40x4 gpuA100x8 gpuMI100x8
#SBATCH --nodes=1
#SBATCH --gpus-per-node=1
##SBATCH --gpu-bind=none     # <- or closest
#SBATCH --tasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16    # <- match to OMP_NUM_THREADS
#SBATCH --mem=40g
#SBATCH --job-name=ditto-sherlock
#SBATCH --time=06:00:00      # hh:mm:ss for the job
##SBATCH --output="Exp_Logging/Company.sherlock.textual.%j.%N.out"
##SBATCH --output="Exp_Logging/Abt.Buy.sherlock.textual.prompt.0.%j.%N.out"
##SBATCH --output="Exp_Logging/iTunes.Amazon.sherlock.dirty.%j.%N.out"
##SBATCH --output="Exp_Logging/DBLP.Google.sherlock.dirty.%j.%N.out"
##SBATCH --output="Exp_Logging/Amazon.Google.sherlock.structured.%j.%N.out"
##SBATCH --output="Exp_Logging/iTunes.Amazon.sherlock.structured.%j.%N.out"
##SBATCH --output="Exp_Logging/DBLP.GoogleScholar.sherlock.structured.%j.%N.out"
#SBATCH --output="Exp_Logging/DBLP.ACM.sherlock.structured.%j.%N.out"
##SBATCH --error="a.out.%j.%N.err"
##SBATCH --mail-user=yirenl2@illinois.edu
##SBATCH --mail-type="BEGIN,END" See sbatch or srun man pages for more email options 
 
export PYTHONPATH=$PYTHONPATH:/projects/bbno/yirenl2/ReFinED/src

# python train_ditto.py --dk sherlock --task Dirty/iTunes-Amazon
# python train_ditto.py --dk sherlock --task Dirty/iTunes-Amazon --prompt 1
# python train_ditto.py --dk sherlock --task Dirty/iTunes-Amazon --prompt 2

# python train_ditto.py --dk sherlock --task Structured/DBLP-ACM
# python train_ditto.py --dk sherlock --task Structured/DBLP-ACM --prompt 1
# python train_ditto.py --dk sherlock --task Structured/DBLP-ACM --prompt 2
# python train_ditto.py --dk sherlock --task Structured/DBLP-GoogleScholar
# python train_ditto.py --dk sherlock --task Structured/DBLP-GoogleScholar --prompt 1
# python train_ditto.py --dk sherlock --task Structured/DBLP-GoogleScholar --prompt 2
# python train_ditto.py --dk sherlock --task Structured/iTunes-Amazon
# python train_ditto.py --dk sherlock --task Structured/iTunes-Amazon --prompt 1
# python train_ditto.py --dk sherlock --task Structured/iTunes-Amazon --prompt 2
# python train_ditto.py --dk sherlock --task Structured/Amazon-Google
# python train_ditto.py --dk sherlock --task Structured/Amazon-Google --prompt 1
# python train_ditto.py --dk sherlock --task Structured/Amazon-Google --prompt 2
# python train_ditto.py --dk sherlock --task Dirty/iTunes-Amazon
# python train_ditto.py --dk sherlock --task Dirty/iTunes-Amazon --prompt 1
# python train_ditto.py --dk sherlock --task Dirty/iTunes-Amazon --prompt 2
# python train_ditto.py --dk sherlock --task Textual/Company
# python train_ditto.py --dk sherlock --task Textual/Company --prompt 1
# python train_ditto.py --dk sherlock --task Textual/Company --prompt 2
# python train_ditto.py --dk sherlock --task Textual/Abt-Buy
# python train_ditto.py --dk sherlock --task Textual/Abt-Buy --prompt 1
# python train_ditto.py --dk sherlock --task Textual/Abt-Buy --prompt 2